version: '3.0'

expectations:
  population_size: 10000

actions:


  generate_study_population:
    run: cohortextractor:latest generate_cohort --index-date-range "2020-05-01 to 2020-12-01 by month" --study-definition study_definition --output-dir=output/inputs
    outputs:
      highly_sensitive:
        cohort: output/inputs/input_*.csv

  generate_study_population_control:
    run: cohortextractor:latest generate_cohort --index-date-range "2020-05-01 to 2020-12-01 by month" --study-definition study_definition_control --output-dir=output/control
    outputs:
      highly_sensitive:
        cohort: output/control/input_control_*.csv
        
        
  generate_study_population_ethnicity:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_ethnicity --output-dir=output/inputs 
    outputs:
      highly_sensitive:     
        cohort: output/inputs/input_ethnicity.csv

  join_ethnicity:
    run: python:latest python analysis/join_ethnicity.py    
    needs: [generate_study_population, generate_study_population_ethnicity]
    outputs:
      highly_sensitive:
        cohort: output/inputs/input*.csv


  join_ethnicity_control:
    run: python:latest python analysis/join_ethnicity_control.py    
    needs: [generate_study_population_control, generate_study_population_ethnicity]
    outputs:
      highly_sensitive:
        cohort: output/control/input*.csv
        
          # Generate measures
          
  generate_measures_control:
      run: cohortextractor:latest generate_measures --study-definition study_definition_control --output-dir=output/control
      needs: [join_ethnicity_control]
      outputs:
        moderately_sensitive:
          measure_csv: output/control/measure_control_*.csv


  generate_measures:
      run: cohortextractor:latest generate_measures --study-definition study_definition --output-dir=output/inputs
      needs: [join_ethnicity]
      outputs:
        moderately_sensitive:
          measure_csv: output/inputs/measure_a*.csv
               
  describe:
    run: python:latest python analysis/descriptives.py
    needs: [generate_measures,join_ethnicity,generate_measures_control]
    outputs:
      moderately_sensitive:
        cohort: output/graphs/*.html
        tables: output/descriptives/descriptive_statistics_*.csv